### ISSUE TITLE
Investigate which energy masks need to be changed for the narrow bin campaign 

### ISSUE THREAD

**Issue by grazwegian** [i4Ds/STIXCore#285]
When the ELUT with the narrow 0.5 keV bins is uploaded the science energy bin boundaries will be changes for the first time. Masks which encode given energy ranges in keV are used in various places and will need to be changed to reflect the new boundaries.
QL Lightcurve 
QL Background 
SumEMask 
Detector failure monitor emask covers the full science range and will not need updated.

**Comment by ennosigaeus** [comment]
QL Lightcurve (QL_BGMON_ENERGY_BIN_MASK2) = 3766493186
QL Background (QL_BGMON_ENERGY_BIN_MASK2) = 3766493186
SumEMask = 0x3FFFFE00

**Comment by nicHoch** [comment]
Latest update from the AX testing:

the switching of previous uploaded ELUTs with TC(37, 18) is working as expected 

first run load LUT0 (default) and after the half time LUT1 (most AD channels go into the upper boundary )

![image](https://user-images.githubusercontent.com/2226714/202400328-033b9ae5-52b8-4c4d-8068-be8340e2aa07.png)

second run other way around

![image](https://user-images.githubusercontent.com/2226714/202401794-6cb9b531-d880-43b2-a615-0b1a959287d4.png)


going back into nominal mode will restore the last activated ELUT

![image](https://user-images.githubusercontent.com/2226714/202403631-f8531f26-4c03-4882-b227-03497d235729.png)


So for this campaign we should upload the ELUT to alternate "Slot" and so can later on switch easy again so that we do not waste TCs. 

Uploading LUT: TC(237,7)
Apply LUT: TC(237,8)
Load ASW parameter: TC(237,18) with parameter ID 132 

all working as expected
